import esbuild from 'esbuild';
import fsp from 'fs/promises';
import { exec } from 'node:child_process';

const run = async (cmd: string) =>
  new Promise<void>((resolve, reject) => exec(cmd, err => {
    if (err) {
      reject(err);
    } else {
      resolve();
    }
  }));

const component = async (name: string) => {
  const [result, struct] = await Promise.all([
    esbuild.build({
      entryPoints: [`src/components/${name}/${name}.ts`],
      outdir: 'tmp',
      platform: 'browser',
      format: 'iife',
      globalName: 'components',
      bundle: true,
      write: false
    }),
    fsp.readFile(`src/components/${name}/${name}.struct.html`),
    esbuild.build({
      entryPoints: [`src/components/${name}/${name}.ts`],
      external: ['@chronocide/dom'],
      outdir: 'dist',
      platform: 'node',
      bundle: true,
      format: 'esm'
    }),
    run(`dts-bundle-generator -o dist/${name}.d.ts src/components/${name}/${name}.ts --export-referenced-types=false --no-banner=true --no-check=true`)
  ]);

  const element = `HTML${name[0].toUpperCase()}${name.slice(1)}Element`;

  await fsp.writeFile(`examples/${name}.html`, [
    '<!-- This file is auto-generated by scripts/build.ts -->',
    '<!DOCTYPE html>',
    '<html lang="en-GB">',
    '<head>',
    '<meta charset="utf-8"></meta>',
    '<meta name="viewport" content="width=device-width,initial-scale=1"></meta>',
    `<title>${name} - @chronocide/web-components</title>`,
    `<script defer>${result.outputFiles[0].text};customElements.define("chrono-${name}", components.${element})</script>`,
    '</head>',
    '<body>',
    '<main>',
    struct,
    '</main>',
    '</body>',
    '</html>'
  ].join(''));
};

await fsp.mkdir('examples', { recursive: true });
await Promise.all([
  component('datagrid')
]);
